### PR TITLE
Stop potentially ongoing metrics on request errors

### PR DESCRIPTION
**Pull request by nickbabcock**
An error in the middle of a request should cause ongoing metrics to reset or stop.

### CODE REVIEW

**Comment by nickbabcock** [comment]
When I load tested the implementation, sometimes the `responseBegin` can trigger even before `onQueue`, which is kinda blowing my mind 💥 , so this PR needs more tweaks to fix the underlying cause.

**Comment by arteam** [comment]
OK, I am going to wait with merging it.

**Comment by dzmitryh** [comment]
Hello guys, do u have any update here ? Was it fixed somewhere or are there any plans to fix it ?

Thanks a lot, Dima.

**Comment by nickbabcock** [comment]
Hmm, it's been a couple years so there may have been a jetty fix (if it's a race condition in the first place)

**Comment by dzmitryh** [comment]
@nickbabcock oki, thx I'll check that!

**Pull request closed without merging**
